---
name: Build Docker Image on Push

on:
  push:
    branches: ["**"]

jobs:
  build:
    uses: ./.github/workflows/_reusable-docker-build.yml
    secrets: inherit
    with:
      image_name: ghcr.io/goauthentik/dev-server
      release: false
